### ISSUE TITLE
Land Acknowledgment

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-syllabus-S20#1]
Reminder to add one, see [tweet about land acknowledgment](https://twitter.com/everestpipkin/status/1208472828590350336?s=11) from @everestpipkin. Anyone reading this I would gladly accept suggestions and recommendations for making a donation.

**Comment by everestpipkin** [comment]
really happy to see this. :) https://aich.org/ is a good option for new york city.

**Comment by shiffman** [comment]
Closing via #2. This is the first time I have added such an acknowledgment so I recognize that I may have made a mistake or omission. Comments and suggestions welcome and encouraged.
